"""
Auto-generated by the OpenMDAO MCP server (export_script, mode='residual').
Standalone, IMPORTABLE reproduction of the DECOUPLED multidisciplinary
consistency residual r(u) = u_supplied - f(x, u) that the evaluate_residual
tool computes (leaf decompose): every inter-discipline feedback edge is
severed and each consumer's coupling input is driven by the SUPPLIED guess of
the coupling variable, not the producer's live output. Severing all the
feedback makes the model a DAG, so one run_model() evaluates each unit once.

Primary use: sample residuals over many points for surrogate training — import
this file and call residuals(u). Run with a Python env that has openmdao.
"""
import os
import importlib.util
import json
import select
import subprocess
import threading
import atexit
import time
import numpy as np
import openmdao.api as om

_script_modules = {}  # abspath -> (mtime, module)
def _import_script(path):
    """Import (cached by path+mtime) a Python module from a file path. Reloads
    automatically if the file changes on disk between runs, so an edited script
    is picked up on the next build without restarting the server."""
    path = os.path.abspath(os.path.expanduser(path))
    if not os.path.isfile(path):
        raise FileNotFoundError(f"Script not found: {path}")
    mtime = os.path.getmtime(path)
    cached = _script_modules.get(path)
    if cached is not None and cached[0] == mtime:
        return cached[1]
    spec = importlib.util.spec_from_file_location(
        f"_omcp_script_{abs(hash(path)) & 0xffffffff}", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    _script_modules[path] = (mtime, module)
    return module

class _ExternalRuntimes:
    """Runs external solve() scripts in helper processes — one reusable helper per
    named runtime, so a slow helper startup is paid once and several runtimes can
    coexist. A component's runtime= label (from add_script_component) selects the
    helper, so e.g. a live MATLAB engine and a compiled-MATLAB mwpython helper run
    side by side. Script-agnostic: each request carries the script path, entry
    point, inputs, and a config dict, so one helper runs any analysis.

    Each runtime is configured entirely by environment variables (no machine
    paths baked in). For a runtime label NAME (upper-cased, non-alphanumerics ->
    '_'; runtime="matlab" -> MATLAB):
      REMDO_RT_<NAME>_LAUNCHER  interpreter that can load that runtime. Required.
      REMDO_RT_<NAME>_RUNNER    generic worker script it executes. Required.
      REMDO_RT_<NAME>_ARGS      optional extra launcher args, space-split.
      REMDO_RT_<NAME>_ENV       optional 'K=V;K=V' env additions for the helper.
    """

    def __init__(self):
        self._procs = {}  # runtime label -> Popen
        self._lock = threading.Lock()

    @staticmethod
    def _key(runtime):
        return "".join(c if c.isalnum() else "_" for c in runtime).upper()

    def _start(self, runtime):
        key = self._key(runtime)
        launcher = os.environ.get(f"REMDO_RT_{key}_LAUNCHER")
        runner = os.environ.get(f"REMDO_RT_{key}_RUNNER")
        missing = [n for n, v in ((f"REMDO_RT_{key}_LAUNCHER", launcher),
                                  (f"REMDO_RT_{key}_RUNNER", runner)) if not v]
        if missing:
            raise RuntimeError(
                f"Script component runtime '{runtime}' is not configured. Set "
                "environment variable(s): " + ", ".join(missing) + ".")
        extra = os.environ.get(f"REMDO_RT_{key}_ARGS", "").split()
        env = dict(os.environ)
        for pair in os.environ.get(f"REMDO_RT_{key}_ENV", "").split(";"):
            if "=" in pair:
                k, v = pair.split("=", 1)
                env[k.strip()] = v
        # Inherit stderr (stderr=None) so a helper's tracebacks/diagnostics reach
        # this server's stderr/logs instead of vanishing — only stdout carries the
        # JSON protocol, so helper stderr is safe to surface and invaluable when a
        # helper fails to start.
        proc = subprocess.Popen(
            [launcher, runner, *extra],
            stdin=subprocess.PIPE, stdout=subprocess.PIPE,
            stderr=None, text=True, bufsize=1, env=env)
        self._procs[runtime] = proc
        atexit.register(self.shutdown)
        return proc

    def call(self, runtime, script_path, function, inputs, config, timeout=300):
        with self._lock:
            proc = self._procs.get(runtime)
            if proc is None or proc.poll() is not None:
                proc = self._start(runtime)
            request = {"script": script_path, "function": function,
                       "inputs": inputs, "config": config}
            proc.stdin.write(json.dumps(request) + "\n")
            proc.stdin.flush()
            deadline = time.time() + timeout
            while True:
                remaining = deadline - time.time()
                if remaining <= 0:
                    raise TimeoutError(f"Runtime '{runtime}' helper did not respond in time.")
                ready, _, _ = select.select([proc.stdout], [], [], remaining)
                if not ready:
                    continue
                line = proc.stdout.readline()
                if line == "":
                    raise RuntimeError(f"Runtime '{runtime}' helper exited unexpectedly.")
                line = line.strip()
                if not line:
                    continue
                try:
                    message = json.loads(line)
                except json.JSONDecodeError:
                    continue  # stray runtime output on stdout — ignore
                if "error" in message:
                    raise RuntimeError(f"Runtime '{runtime}' helper error: {message['error']}")
                return message["result"]

    def shutdown(self):
        for proc in self._procs.values():
            if proc.poll() is None:
                try:
                    proc.terminate()
                except Exception:
                    pass
        self._procs = {}

_external_runtimes = _ExternalRuntimes()

class ScriptComp(om.ExplicitComponent):
    """An ExplicitComponent that delegates compute to a function in an external
    Python script (a CFD/FEM solver, a legacy analysis, ...). The spec records the
    script path, entry-point function name, the input/output names, and the
    call_style. On compute the function is called either with one dict
    {input_name: value} (call_style 'dict', returning {output_name: value}) or with
    positional values in declared order (call_style 'positional', returning a
    value/tuple/dict). Partials are finite-differenced (or complex-stepped) by
    OpenMDAO — a black box has no closed form — so every (output, input) pair is
    declared 'fd'/'cs'. The spec is the same discipline dict add_script_component
    records; _build passes it in as 'spec'.

    Variables are scalar by default. Pass 'sizes' (a {var_name: int} map built at
    build time from the values flowing through) to make any of them length-n
    vectors: a size-n input is handed to the script as a numpy array (a size-1 one
    stays a plain float, so existing scalar scripts are unchanged), and OpenMDAO
    finite-differences the resulting (possibly larger) Jacobian as before."""

    def initialize(self):
        self.options.declare("spec", types=dict)
        # {var_name: length}; absent vars default to 1 (scalar). None == all scalar.
        self.options.declare("sizes", types=dict, default=None)
        self._fn = None  # entry-point callable, loaded lazily and cached

    def _size(self, name):
        return (self.options["sizes"] or {}).get(name, 1)

    def setup(self):
        spec = self.options["spec"]
        for iname in spec["inputs"]:
            self.add_input(iname, val=np.ones(self._size(iname)))
        for oname in spec["outputs"]:
            self.add_output(oname, val=np.ones(self._size(oname)))

    def setup_partials(self):
        # A black box is differentiated numerically end-to-end.
        self.declare_partials("*", "*", method=self.options["spec"].get("derivatives", "fd"))

    def _load(self):
        if self._fn is not None:
            return self._fn
        spec = self.options["spec"]
        module = _import_script(spec["script_path"])
        fn = getattr(module, spec["function"], None)
        if fn is None:
            raise AttributeError(
                f"Script '{spec['script_path']}' has no function '{spec['function']}'.")
        if not callable(fn):
            raise TypeError(
                f"'{spec['function']}' in '{spec['script_path']}' is not callable.")
        self._fn = fn
        return fn

    @staticmethod
    def _to_output_dict(raw, spec):
        """Map a script's return value onto declared outputs. A dict is keyed by
        output name (any call_style). For call_style='positional': a tuple/list
        zips with declared outputs (lengths must match); a bare scalar fills the
        single declared output (error if more than one is declared)."""
        out_names = spec["outputs"]
        where = f"'{spec['function']}' in '{spec['script_path']}'"
        # Each value is coerced to a 1-D float array; a scalar return becomes
        # shape (1,), a vector keeps its length. OpenMDAO checks it against the
        # declared output shape on assignment.
        as_arr = lambda v: np.atleast_1d(np.asarray(v, dtype=float))
        if isinstance(raw, dict):
            missing = [o for o in out_names if o not in raw]
            if missing:
                raise KeyError(f"{where} did not return output(s) {missing}. "
                               f"Returned keys: {sorted(raw)}.")
            return {o: as_arr(raw[o]) for o in out_names}
        if spec.get("call_style", "dict") == "positional":
            if isinstance(raw, (tuple, list)):
                if len(raw) != len(out_names):
                    raise ValueError(f"{where} returned {len(raw)} value(s) but "
                                     f"{len(out_names)} output(s) are declared.")
                return {o: as_arr(v) for o, v in zip(out_names, raw)}
            if len(out_names) != 1:
                raise ValueError(f"{where} returned a single value but "
                                 f"{len(out_names)} outputs are declared — return a "
                                 "tuple/list or a dict.")
            return {out_names[0]: as_arr(raw)}
        raise TypeError(f"{where} must return a dict of {{output_name: value}}, "
                        f"got {type(raw).__name__}.")

    def compute(self, inputs, outputs):
        spec = self.options["spec"]
        # A size-1 input is passed as a plain float (so existing scalar scripts are
        # unchanged); a vector input is passed as its numpy array.
        in_vals = {}
        for name in spec["inputs"]:
            arr = np.asarray(inputs[name], dtype=float)
            in_vals[name] = float(arr[0]) if arr.size == 1 else arr
        call_style = spec.get("call_style", "dict")
        runtime = spec.get("runtime", "inprocess")
        if runtime != "inprocess":
            # Script can't run in this process (e.g. compiled MATLAB on macOS):
            # delegate to the shared helper for this runtime. The config carries
            # the component's input/output names and call_style plus anything the
            # user passed, so a generic adapter can run any analysis without
            # per-script Python. Arrays are JSON-encoded as lists for the helper.
            config = dict(spec.get("config") or {})
            config.setdefault("inputs", list(spec["inputs"]))
            config.setdefault("outputs", list(spec["outputs"]))
            config.setdefault("call_style", call_style)
            payload = {k: (v.tolist() if isinstance(v, np.ndarray) else v)
                       for k, v in in_vals.items()}
            raw = _external_runtimes.call(
                runtime, spec["script_path"], spec["function"], payload, config)
        elif call_style == "positional":
            raw = self._load()(*(in_vals[name] for name in spec["inputs"]))
        else:
            raw = self._load()(in_vals)
        mapped = self._to_output_dict(raw, spec)
        for oname in spec["outputs"]:
            outputs[oname] = mapped[oname]


# ---------------------------------------------------------------------------
# Decoupled-residual structure, baked at export from the SAME inference the
# evaluate_residual oracle uses (infer_coupling) — not re-derived from the
# connect calls, so promotion-wired coupling is covered identically.
# ---------------------------------------------------------------------------
# Severed feedback edges {consumer_input: producing_output}: each consumer
# input is driven by the guess of the producing output, not its live value.
COUPLING_INPUTS = {'res.Peng_out': 'perf.Peng',
                   'res.Tbulk_fem': 'fem.Tbulk',
                   'res.recon_out': 'econ.recon',
                   'res.tfail_out': 'life.tfail'}
# Residual targets, keyed by the PRODUCING output.
COUPLING_VARS = ['econ.recon', 'fem.Tbulk', 'life.tfail', 'perf.Peng']
# Recorded augmented point (set_initial_value snapshot, promotion-resolved).
RECORDED_STATE = {'fem.K': 30.0,
                  'fem.Tc1': 600.0,
                  'fem.Tc2': 650.0,
                  'fem.Tc3': 700.0,
                  'fem.hle': 2000.0,
                  'fem.hte': 1000.0,
                  'life.Plm': 25000.0,
                  'life.Tbulk': 1100.0,
                  'perf.Fperf': 0.9,
                  'perf.Tg': 1250.0,
                  'perf.mdot': 0.12,
                  'econ.Fecon': 1.0,
                  'econ.Peng': 5500000.0,
                  'econ.tfail': 50.0}
# Inputs of each producing unit (leaf discipline).
UNIT_INPUTS = {'fem': ['K', 'Tc1', 'Tc2', 'Tc3', 'hle', 'hte'],
               'life': ['Plm', 'Tbulk'],
               'perf': ['Fperf', 'Tg', 'mdot'],
               'econ': ['Fecon', 'Peng', 'tfail']}
# Promoted endpoints that share one value: a u override on any member
# overrides all of them.
PROMOTION_SIBLINGS = {}
_DEFAULT_RETURN_MAP = False


def _build_decoupled():
    """One OpenMDAO problem holding every producing unit as an INDEPENDENT
    subsystem — no inter-discipline connection or promotion is emitted, so the
    feedback is severed and a single run_model() evaluates each unit exactly
    once. Inputs/outputs are addressed by their plain 'disc.var' name."""
    prob = om.Problem(reports=False)
    prob.model = om.Group()
    _spec_0 = {'name': 'fem',
               'kind': 'script',
               'script_path': '/Users/joeflanagan/Downloads/fem_heat_solve.py',
               'function': 'solve',
               'inputs': ['hle', 'hte', 'K', 'Tc1', 'Tc2', 'Tc3'],
               'outputs': ['Tbulk'],
               'derivatives': 'fd',
               'runtime': 'matlab_compiled',
               'config': {},
               'call_style': 'dict'}
    prob.model.add_subsystem('fem', ScriptComp(spec=_spec_0))
    _spec_1 = {'name': 'life',
               'kind': 'script',
               'script_path': '/Users/joeflanagan/Downloads/lifetime.py',
               'function': 'lifetime',
               'inputs': ['Plm', 'Tbulk'],
               'outputs': ['tfail'],
               'derivatives': 'fd',
               'runtime': 'inprocess',
               'config': {},
               'call_style': 'positional'}
    prob.model.add_subsystem('life', ScriptComp(spec=_spec_1))
    _spec_2 = {'name': 'perf',
               'kind': 'script',
               'script_path': '/Users/joeflanagan/Downloads/performance.py',
               'function': 'performance',
               'inputs': ['mdot', 'Tg', 'Fperf'],
               'outputs': ['Peng'],
               'derivatives': 'fd',
               'runtime': 'inprocess',
               'config': {},
               'call_style': 'positional'}
    prob.model.add_subsystem('perf', ScriptComp(spec=_spec_2))
    _spec_3 = {'name': 'econ',
               'kind': 'script',
               'script_path': '/Users/joeflanagan/Downloads/economics.py',
               'function': 'economics',
               'inputs': ['Fecon', 'tfail', 'Peng'],
               'outputs': ['recon'],
               'derivatives': 'fd',
               'runtime': 'inprocess',
               'config': {},
               'call_style': 'positional'}
    prob.model.add_subsystem('econ', ScriptComp(spec=_spec_3))
    prob.setup()
    return prob


_PROB = _build_decoupled()


def residuals(u=None, return_map=_DEFAULT_RETURN_MAP):
    """Decoupled multidisciplinary consistency residual r(u) = u_supplied -
    f(x, u), leaf decompose — the exact quantity evaluate_residual computes.

    Every inter-discipline feedback edge is severed: each consumer's coupling
    input is driven by the SUPPLIED guess of the coupling variable (the decisive
    line `state[COUPLING_INPUTS[full]]`), NOT by the producer's live output.

    u: optional {'disc.var': value} overriding RECORDED_STATE (a value on any
       promoted endpoint overrides all its siblings). Omitted entries fall back
       to the recorded value, then to the component default. return_map=True
       returns the discipline output maps f instead of the residual u_supplied-f.
    Returns (result, norm): result maps each coupling variable to its residual
    (or output-map) ndarray; norm is the L2 norm over the flattened stack.
    """
    state = dict(RECORDED_STATE)
    for _k, _v in (u or {}).items():
        for _sib in PROMOTION_SIBLINGS.get(_k, (_k,)):
            state[_sib] = _v
    prob = _PROB
    for _unit, _in_names in UNIT_INPUTS.items():
        for _name in _in_names:
            _full = f"{_unit}.{_name}"
            if _full in COUPLING_INPUTS:                 # severed: feed the guess
                prob.set_val(_full, np.asarray(state[COUPLING_INPUTS[_full]], dtype=float))
            elif _full in state:                         # x / shared input
                prob.set_val(_full, np.asarray(state[_full], dtype=float))
            # else: leave the component default (1.0), as the oracle does.
    prob.run_model()
    result = {}
    for _cv in COUPLING_VARS:
        _f = np.asarray(prob.get_val(_cv), dtype=float).flatten()
        if _cv not in state:
            raise KeyError(
                f"coupling variable {_cv!r} has no supplied (u) or recorded "
                f"value to subtract against — pass it in u.")
        _guess = np.asarray(state[_cv], dtype=float).flatten()
        result[_cv] = _f if return_map else (_guess - _f)
    _stack = (np.concatenate([result[k] for k in result]) if result
              else np.array([]))
    return result, float(np.linalg.norm(_stack))


if __name__ == "__main__":
    _res, _norm = residuals()        # at the recorded / exported augmented point
    for _k, _val in _res.items():
        print(f"R({_k}) = {float(_val[0]) if _val.size == 1 else _val}")
    print("residual_norm =", _norm)
